version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data

  airflow-webserver:
    image: apache/airflow:2.9.1
    depends_on:
      - postgres
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__WEBSERVER__SECRET_KEY: test_secret
      _AIRFLOW_WWW_USER_USERNAME: airflow
      _AIRFLOW_WWW_USER_PASSWORD: airflow
      AIRFLOW__LOGGING__LOGGING_LEVEL: DEBUG
    volumes:
      - your_path/sftp_transfer/dags:/opt/airflow/dags
      - your_path/sftp_transfer:/opt/airflow/sftp_transfer
    ports:
      - "8080:8080"
    command: webserver

  airflow-scheduler:
    image: apache/airflow:2.9.1
    depends_on:
      - airflow-webserver
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__LOGGING__LOGGING_LEVEL: DEBUG
    volumes:
      - your_path/sftp_transfer/dags:/opt/airflow/dags
      - your_path/sftp_transfer:/opt/airflow/sftp_transfer
    command: scheduler

  sftp:
      image: atmoz/sftp
      ports:
        - "2222:22"
      command: foo:pass:::upload


volumes:
  postgres-db-volume:
